#+TITLE: 認知科学会 オーガナイズド・セッション
#+AUTHOR: Kohske Takahashi
#+LANGUAGE: en
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="//www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="//www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>

#+OPTIONS: toc:nil num:nil html5-fancy:t \n:t


* 過剰に意味を創り出す認知：ホモ・クオリタスとしての人間理解へ向けて 
  
#+BEGIN_CENTER
file:pareh.png 　　file:107329r.png file:ayatsuri.png 　　file:230226.png
#+END_CENTER

日本認知科学会第34回大会にて *「過剰に意味を創り出す認知：ホモ・クオリタスとしての人間理解へ向けて」*
というタイトルのオーガナイズド・セッションを企画しました。

多くの方のご来場をお待ちしております。

- 日時: 2017年9月15日 (金) 13:00-15:30
- 場所: 金沢大学角間キャンパス 101講義室
- 論文集: http://www.jcss.gr.jp/meetings/jcss2017/proceedings/OS05.html
- ウェブサイト： http://www.jcss.gr.jp/meetings/jcss2017/

** スケジュール

- 13:00-13:05 イントロダクション :: 高橋 康介 (中京大学) 
- 13:05-13:40 多感覚を統合したがる自己：なぜ身体所有感を感じてしまうのか :: 小川 奈美 (東京大学・依頼講演)
- 13:40-14:15 現実感が道理をしのぐ時：神経疾患患者の幻覚体験にそなわる現実感 :: 西尾 慶之 (東北大学・依頼講演) 
- 14:15-14:35 間隙をつくる障害物の“人らしさ”は，通り抜け行為に影響を与えるか？−間隙の通過可否判断研究からの一考察 :: 友野 貴之 (早稲田大学)
- 14:35-14:55 新たな減価効果—顔の多重重複は不気味さを生む— :: 米満 文哉 (九州大学) 
- 14:55-15:15 特徴の統合によるオブジェクト構成の計算論に向けて :: 日高 昇平 (JAIST)
- 15:15-15:30 :: 総合ディスカッション

** 概要

　人が認識する世界は「意味」に満ちている。これらの「意味」は世界の姿を正しい映し出したものなのだろうか。「意味」はどこから現れるのだろうか。よく観察してみると、人の認知には「過剰に意味を創り出す」という性質が備わっているようである。

　例を挙げよう。「∵」 を顔として認識する（パレイドリア）。幾何学図形の動きから意図やアニマシーを見出す（アニマシー知覚）。自分自身のいい加減な意思決定に合理的な説明を与えてしまう（認知バイアスや選択盲）。ゴムの手を自分の身体として錯覚する（ラバーバンド錯覚）。外界の変化が自分自身の動きに帰属すると感じる（動作主体感）。これらはいずれも認知心理学の分野で広く知られた現象である。過剰に意味を創り出す例はさらに、思考や推論にまで広く見られる。枯れすすきは幽霊となって現れる。虫の知らせや験担ぎでは、無関係な事象の間に超自然的な因果を認識する。天変地異には神々の、流行病には悪霊の力を感じることもある。

　このように人はノイズをノイズのまま、偶然を偶然のまま無意味なものとして認識するのではなく、ノイズに有意味なパターンを知覚し、偶然の事象に因果を認識する。これは文化や社会の成熟、そして人類知性の進化にどう貢献したのだろうか。果たして動物は、未来のAIは、過剰な意味を創り出し認識するのだろうか。本セッションは、知覚から思考、推論に至るまでこれまではバラバラに捉えられてきたさまざまな現象を、「過剰に意味を創り出す」という一貫した枠組みの中で理解しようという試みである。そしてこの人間観を「ホモ・クオリタス」と呼び、認知の基本的な原理として位置づけることを提案したい。

** キーワード

意味・質感・芸術・（知覚・認知・身体の）錯覚・創造力・想像力・空想・感情や情動・人工物の擬人化・意図推定・遊び・超自然的な力の認知・間（ま）の感覚・クオリアなど。

** 関連コンテンツ

- [[http://chitosepress.com/2016/09/28/2320/][意味を創る――生きものらしさの認知心理学（高橋によるサイナビ連載）]]
- [[http://kohske.github.io/research/parews01/][第１回 パレイドリア研究会]]
- [[http://kohske.github.io/research/parews02/][第２回 パレイドリア研究会]]


- [[https://www.youtube.com/watch?v=xgHrfycNstU][えくす手／Metamorphosis Hand (小川奈美先生による身体所有感に関する作品)]]
- [[http://www.moguravr.com/metamorphosis-hand-interview/][「人間を知るためのVR」（小川奈美先生インタビュー）]]


** 企画・司会

- 高橋 康介（中京大学）
- 日高 昇平（北陸先端科学技術大学院大学）


** 連絡先・お問い合わせ :: http://kohske.github.io/chukyo/img/email_ktakahashi.png

#+BEGIN_HTML
<span style="font-size: 50%">本研究会は科学研究費補助金若手A「生き物らしさ認知の心的過程とその応用」「力学系の不変量による身体運動の分節化・認識・生成理論の構築」の補助を受けております。</span>
#+END_HTML

   
