#+TITLE: 認知科学会 オーガナイズド・セッション
#+AUTHOR: Kohske Takahashi
#+LANGUAGE: en
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>

#+OPTIONS: toc:nil num:nil html5-fancy:t

* 過剰に意味を創り出す認知：ホモ・クオリタスとしての人間理解へ向けて 

#+BEGIN_CENTER
file:pareh.png 　　file:107329r.png file:ayatsuri.png 　　file:230226.png
#+END_CENTER

日本認知科学会第34回大会にて *「過剰に意味を創り出す認知：ホモ・クオリタスとしての人間理解へ向けて」*
というタイトルのオーガナイズド・セッションを企画しています。

現在、講演発表を募集中です。認知科学に隣接するさまざまな分野からの応募も大歓迎です。関連するネタをお持ちの方は、奮ってご応募ください。

*※ 発表申込締切 2017年 4 月 3 日 (月)*


- 日時: 2017年9月13日 (水)〜9月15日（金）
- 場所: 金沢大学角間キャンパス
- ウェブサイト： http://www.jcss.gr.jp/meetings/jcss2017/


** 概要

　人が認識する世界は「意味」に満ちている。これらの「意味」は世界の姿を正しい映し出したものなのだろうか。「意味」はどこから現れるのだろうか。よく観察してみると、人の認知には「過剰に意味を創り出す」という性質が備わっているようである。

　例を挙げよう。「∵」 を顔として認識する（パレイドリア）。幾何学図形の動きから意図やアニマシーを見出す（アニマシー知覚）。自分自身のいい加減な意思決定に合理的な説明を与えてしまう（認知バイアスや選択盲）。ゴムの手を自分の身体として錯覚する（ラバーバンド錯覚）。外界の変化が自分自身の動きに帰属すると感じる（動作主体感）。これらはいずれも認知心理学の分野で広く知られた現象である。過剰に意味を創り出す例はさらに、思考や推論にまで広く見られる。枯れすすきは幽霊となって現れる。虫の知らせや験担ぎでは、無関係な事象の間に超自然的な因果を認識する。天変地異には神々の、流行病には悪霊の力を感じることもある。

　このように人はノイズをノイズのまま、偶然を偶然のまま無意味なものとして認識するのではなく、ノイズに有意味なパターンを知覚し、偶然の事象に因果を認識する。これは文化や社会の成熟、そして人類知性の進化にどう貢献したのだろうか。果たして動物は、未来のAIは、過剰な意味を創り出し認識するのだろうか。本セッションは、知覚から思考、推論に至るまでこれまではバラバラに捉えられてきたさまざまな現象を、「過剰に意味を創り出す」という一貫した枠組みの中で理解しようという試みである。そしてこの人間観を「ホモ・クオリタス」と呼び、認知の基本的な原理として位置づけることを提案したい。

** キーワード

意味・（知覚・身体の）錯覚・創造力・想像力・空想・感情や情動・人工物の擬人化・意図推定・遊び、超自然的な力の認知、間（ま）の感覚など。

** 講演者(予定)

# - 宮原 克典 (JSPS海外特別研究員・ハーバード大学)：哲学・現象学
- 哲学者 X氏
- 小川 奈美 (東京大学)：VR工学


- 高橋 康介 (中京大学)・日高 昇平 (JAIST)：認知科学
 
** 関連コンテンツ

- [[http://chitosepress.com/2016/09/28/2320/][意味を創る――生きものらしさの認知心理学（高橋によるサイナビ連載）]]
- [[http://kohske.github.io/research/parews01/][第１回 パレイドリア研究会]]
- [[http://kohske.github.io/research/parews02/][第２回 パレイドリア研究会]]


- [[https://www.youtube.com/watch?v=xgHrfycNstU][えくす手／Metamorphosis Hand (小川奈美先生による身体所有感に関する作品)]]
- [[http://www.moguravr.com/metamorphosis-hand-interview/][「人間を知るためのVR」（小川奈美先生インタビュー）]]


** 企画・司会

- 高橋 康介（中京大学）
- 日高 昇平（北陸先端科学技術大学院大学）


** 連絡先・お問い合わせ :: file:email_kt.png

#+BEGIN_HTML
<span style="font-size: 50%">本研究会は科学研究費補助金若手A「生き物らしさ認知の心的過程とその応用」「力学系の不変量による身体運動の分節化・認識・生成理論の構築」の補助を受けております。</span>
#+END_HTML

